package com.boeing.apmapi.common.interfaces;

import com.boeing.apmapi.model.NoteNode;
import com.boeing.apmapi.model.TaskNode;
import com.boeing.apmapi.common.Utils.ApiDataTypes;
import com.boeing.apmapi.model.ClientNode;
import com.boeing.apmapi.model.Empty;
import com.boeing.apmapi.model.EngagementVersionNode;
import com.boeing.apmapi.model.Error;
import com.boeing.apmapi.model.FunctionNode;
import com.boeing.apmapi.model.FunctionalAreaNode;
import com.boeing.apmapi.model.FunctionalGroupNode;
import com.boeing.apmapi.model.Graph;
import com.boeing.apmapi.model.NodeList;
import com.boeing.apmapi.model.SaveVersionNode;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonIgnoreProperties(value = "elementType", // ignore manually set elementType, it will be automatically generated by
                                             // Jackson during serialization
        allowSetters = true // allows the elementType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "elementType", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ClientNode.class, name = "CVV"),
        @JsonSubTypes.Type(value = EngagementVersionNode.class, name = "EVV"),
        @JsonSubTypes.Type(value = Empty.class, name = "Empty"),
        @JsonSubTypes.Type(value = Error.class, name = "Error"),
        @JsonSubTypes.Type(value = FunctionalAreaNode.class, name = "FNA"),
        @JsonSubTypes.Type(value = FunctionNode.class, name = "FNC"),
        @JsonSubTypes.Type(value = FunctionalGroupNode.class, name = "FNG"),
        @JsonSubTypes.Type(value = Graph.class, name = "Graph"),
        @JsonSubTypes.Type(value = NoteNode.class, name = "NTT"),
        @JsonSubTypes.Type(value = NodeList.class, name = "NodeList"),
        @JsonSubTypes.Type(value = TaskNode.class, name = "TKK"),
        @JsonSubTypes.Type(value = FunctionalAreaNode.class, name = "ApmFnaNode"),
        @JsonSubTypes.Type(value = FunctionNode.class, name = "ApmFncNode"),
        @JsonSubTypes.Type(value = FunctionalGroupNode.class, name = "ApmFngNode"),
        @JsonSubTypes.Type(value = NoteNode.class, name = "ApmNote"),
        @JsonSubTypes.Type(value = TaskNode.class, name = "ApmTaskNode"),
        @JsonSubTypes.Type(value = ClientNode.class, name = "ClientNode"),
        @JsonSubTypes.Type(value = EngagementVersionNode.class, name = "EngagementNode"),
        @JsonSubTypes.Type(value = SaveVersionNode.class, name = "SaveVersionNode")
})

public interface IElement {
    public ApiDataTypes getApiDataType();
}
